spring:
  profiles:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/talents?serverTimezone=UTC&characterEncoding=UTF-8
    username:  root
    password:  123456
    driverClassName: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    #设置方言指定默认生成表的存储引擎为InnoDB
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

  redis:
    #数据库
    database: 0
    #服务器地址
    host: 127.0.0.1
    #服务器端口
    port: 6379
    #连接密码：
    password:
    #连接池
    pool:
      max-active: 8
      max-wait: 1
      max-idle: 10
      min-idle: 1

author:
  ignoreUrls: /login

### jwt
jwt:
  header:
  secret:
  expiration:
  tokenHead:
  route:
